language: java

jdk:
    - oraclejdk8

sudo: false

before_script:
    - cd jyhton
    - export INSTALLATION_ROOT="."
    - uname -a
    - printenv

script:
    - pwd
    - jdk_switcher use oraclejdk7
    - ant antlr_gen
    - jdk_switcher use oraclejdk8
    - ant

after_script:
    - export INSTALLATION_ROOT="."
    - dist/bin/jython nativeSIMunitTests.py
    - dist/bin/jython ReLUnitTests.py
    - dist/bin/jython SPARQLUnitTests.py
