language: java

jdk:
    - openjdk7
    - oraclejdk8

sudo: false

before_script:
    - cd jyhton
    - export INSTALLATION_ROOT="."
    - uname -a
    - printenv

script:
    - jdk_switcher use openjdk7
    - echo "Building with Java 7"
    - pwd
    - ant

after_success:
    - jdk_switcher use oraclejdk8

after_script:
    - dist/bin/jython nativeSIMunitTests.py
    - dist/bin/jython SPARQLUnitTests.py
