language: java

jdk:
    - openjdk7
    - openjdk8

sudo: false

before_script:
    - cd jyhton
    - export INSTALLATION_ROOT="."
    - uname -a
    - printenv

script:
    - ant
    - ant
    - ./sim_native_tests.sh
