language: java

jdk:
    - oraclejdk8
matrix:
    allow_failures:
        - jdk: oraclejdk8

sudo: false

before_script:
    - cd jyhton
    - export INSTALLATION_ROOT="."
    - uname -a
    - printenv

script:
    - pwd
    - ant

after_success:
    - jdk_switcher use oraclejdk8

after_script:
    - dist/bin/jython nativeSIMunitTests.py
    - dist/bin/jython SPARQLUnitTests.py
    - dist/bin/jython ReLUnitTests.py
